### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by dkameneck** [uphold/uk-modulus-checking#11]
Hi!
I have problems importing this module.
After installing it via npm and importing it like:

import UkModulusChecking from 'uk-modulus-checking/src'
import UkModulusChecking from 'uk-modulus-checking'
var UkModulusChecking = require('uk-modulus-checking')

I always end up with the same error:

This dependency was not found:
* fs in ./~/uk-modulus-checking/src/index.js
To install it, you can run: npm install --save fs

I tried installing fs, but it doesn't change anything.
I am using Vue.js on my project.
Looks like I am missing something to do before importing

**Comment by franciscocardoso** [comment]
Hi @dkameneck ,

Did you try using the `dist` file instead?

This should work.

```js
const ukModulusChecking = require("uk-modulus-checking");

new ukModulusChecking({ accountNumber: '<accountNumber>', sortCode: '<sortCode>' }).isValid();
```

**Comment by dkameneck** [comment]
Hey the issue was in 'fs" module.
I tryed running it in browser, which was stupid.
Thanks for your time anyway!

**Comment by leotm** [comment]
Hey @dkameneck , just trying to implement this check into a form in .vue page here too.
How did you do it in the end?

**Comment by dkameneck** [comment]
Hey @leotm !

My problem was with opening that file with rules. I simply converted that .json file to .js.
After that I imported that js file and loaded it without using fs module.
On top of that, you have to change each file in this project to work with vue. (atleast I did it).

If you don't understand what I did, let me know, I still have whole project converted to work with vue apps, and without using fs module.

Btw. fs module opens files, which is "forbidden" on client side, otherwise writing trojans would be super easy.

**Comment by leotm** [comment]
Thanks @dkameneck ! Which file were you trying to open with which rules?
The only .json i'm seeing is *package.json*.
If you still have the project to work with Vue without using fs and could attach it here or upload it, that would be great.

**Comment by dkameneck** [comment]
Hey @leotm !
I was talking about files data/scsubtab and data/valacdos. I am not sure which format were they before.
Can I email it to you?

**Comment by dkameneck** [comment]
[ukmodulus.zip](https://github.com/uphold/uk-modulus-checking/files/1632410/ukmodulus.zip)

Nvm, didn't notice that i can upload it here at first.
You can use it now by simply importing it:
`import UkModulusChecking from './UkModulusChecking.js'`

**Comment by connorwyatt** [comment]
@franciscocardoso Is there any reason that you wouldn't be open to incorporating such a fix into the main project?

**Comment by connorwyatt** [comment]
If you are interested I have a fork that I can create a PR for: https://github.com/uphold/uk-modulus-checking/compare/master...connorwyatt:master
