### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by leotm** [uphold/uk-modulus-checking#12]
`import UkModulusChecking from 'uk-modulus-checking';`
or
`const UkModulusChecking = require('uk-modulus-checking')`

throwing

`client?843a:157 ./~/uk-modulus-checking/dist/index.js

Module not found: Error: Can't resolve 'fs' in '/Users/Leo/Documents/Projects/thehouseshop/public/rentscore-app/node_modules/uk-modulus-checking/dist'`

**Comment by leotm** [comment]
https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285598881 resolved the error.

But now getting `Uncaught TypeError: _fs2.default.readFileSync is not a function`.

**Comment by franciscocardoso** [comment]
Hi @leotm 

Did you see this issue: https://github.com/uphold/uk-modulus-checking/issues/11?

**Comment by leotm** [comment]
Ah, thanks @franciscocardoso , looks very relevant, I will follow the suggestions there now.

**Comment by leotm** [comment]
Still getting the same results above :( even with

`import UkModulusChecking from 'uk-modulus-checking/dist';`
or
`const UkModulusChecking = require('uk-modulus-checking/dist')`

**Comment by leotm** [comment]
Ah, seems my aim is to do this validation client-side via the browser with just JavaScript, not server-side with node.

As the browser has no access to file system.

Yep, silly me, trying to run in client-side in a Vue form via the browser.
